apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bad-medium-db
  description: Base de datos PostgreSQL medium (dev) solicitada por Golden Path
  annotations:
    parkglobal.io/cost-center: CC-PARK-01
    parkglobal.io/secret-ref: bad-medium-db-app
    backstage.io/kubernetes-namespace: team-parking-core
  tags: [postgresql, golden-path, dev]
spec:
  type: database
  owner: group:team-parking-core
  system: parking
