apiVersion: platform.parkglobal.io/v1alpha1
kind: DatabaseClaim
metadata:
  name: e2e-db
  namespace: team-parking-core
spec:
  owner:
    team: parking-core
    costCenter: CC-PARK-01
  engine: postgresql
  size: small
  environment: dev
  access:
    readers: [grp-parking-core]
